services:
  - type: web
    name: miabe-pharmacie
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
